### PR TITLE
feat(case-monitoring): progressively highlight path of supplier

### PR DESCRIPTION
**Pull request by tbouffard**
Highlight the first sub-path when starting the process (from start to )
Then, highlight the  "review and adapt email" activity and decrease the opacity of the first sub-path.

### CODE REVIEW

**Comment by tbouffard** [comment]
### 1st implementation


https://user-images.githubusercontent.com/27200110/225979009-04046e37-1d94-4720-8a9c-c8828393be58.mp4

**Comment by assynour** [comment]
> ### 1st implementation

Very nice effect already :) there's a bug in the popover and textarea size in the second popover

**Comment by tbouffard** [comment]
### 2nd implementation

Also increase the opacity of the first sub-path when displaying the "review and adapt email"

image

**Review by assynour — APPROVED** [review]
👍

**Pull request merged**
