### PR TITLE
feat(case-monitoring): improve design activities

### LINKED ISSUE #56: [FEAT] Review the general style of the demo
While implementing this, also consider #35

```[tasklist]
### Tasks
- [x] ~popover theme (background color, border, shadow, ...)~ won't do
- [x] popover buttons #42 (#99)
- [x] case monitoring late task: remove the overlay (#100)
- [x] case monitoring late task: change fill color. Try #f9b842.  (#100)
- [x] ~case monitoring supplier contact: color, opacity and stroke width of the highlighted path~ won't do
- [x] case monitoring supplier contact: popover. Margin/Padding top/margin between textarea + between prompt and button. Margin padding with the popover border (#99)
- [x] case monitoring sub process: tasks highlight shadow-box, overlays, current running task (it is late, so use the same style as for the late sub-process element in the main process)  (#100)
- [x] case monitoring sub process: popover - add padding (#99)
```

### PR DESCRIPTION
**Pull request by assynour**
closes #56 

- Remove the "?" overlay
- Set the color of the late-running activities to #f9b842 as proposed in #56
- Homogenize the colors of the late-running activities
- Update the colors in the sub-process to be harmonized with the new #f9b842 color.  Variations of blue are used, similarly to the colors used in the supplier process.

### CODE REVIEW

**Comment by assynour** [comment]
@tbouffard The 2 variants are below for better comparison. I feel that the "blueviolet" matches better without the pulse effect.

blueviolet

blue

**Comment by assynour** [comment]
@tbouffard: The 2 variants are below for better comparison. I feel that the "blueviolet" matches better without the pulse effect.

blueviolet

blue

**Comment by tbouffard** [comment]
> @tbouffard The 2 variants are below for better comparison. I feel that the "blueviolet" matches better without the pulse effect.

yes, I agree, I also prefer the "blueviolet".

**Comment by assynour** [comment]
> > @tbouffard The 2 variants are below for better comparison. I feel that the "blueviolet" matches better without the pulse effect.
> 
> yes, I agree, I also prefer the "blueviolet".

fixed in [257e11d](https://github.com/process-analytics/bonita-day-demo-2023/pull/100/commits/257e11d9b7a7827fbed98dca1d3316697b138e3c)

**Review by tbouffard — APPROVED** [review]
LGTM

**Pull request merged**
